; Corresponds to the PCB in the repository
[env:esp32_s3_supermini]
monitor_raw = true
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-s3-fh4r2 ; 4MB flash, 2MB psram
board_build.partitions = ../wqvblink_partition_table.csv
lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.16
	adafruit/Adafruit GFX Library@^1.12.4
build_flags =
	-DENABLE_DISPLAY_128x64=1
	-DPIN_I2C_SDA=8
	-DPIN_I2C_SCL=9
	-DPIN_IRDA_RX=7
	-DPIN_IRDA_TX=6
	-DLOG_LEVEL=3
	-DSCREEN_ROTATION=2


; For unit testing
[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++20