[env]
monitor_raw = true
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board_build.partitions = noota_3gffat.csv ;3.0MB FFAT
; noota_ffat.csv ;2.0MB FFAT
; default_ffat.csv ;1.4MB FFAT
lib_deps =
build_flags =

; Corresponds to the PCB in the repository
[env:esp32_s3_supermini]
board = esp32-s3-fh4r2 ; 4MB flash, 2MB psram
build_flags =
	-DPIN_IRDA_RX=7
	-DPIN_IRDA_TX=6