; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_raw = true

[common]
platform_esp32_espressif = espressif32
platform_esp32_pioarduino = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
lib_deps =
build_flags =
partitions = default_ffat.csv

; Completely optional 128x64 SSD1306 OLED screen for status
[ssd1306]
lib_deps =
	adafruit/Adafruit SSD1306@^2.5.16
	adafruit/Adafruit GFX Library@^1.12.4
build_flags = -DENABLE_SSD1306

; Completely optional PSRAM as destination for watch dump, falls back to flash
[psram]
lib_deps = tobozo/ESP32-PSRamFS@^1.0.7
build_flags = -DENABLE_PSRAM

[env:lolin_s2_mini]
platform = ${common.platform_esp32_pioarduino}
framework = arduino
board = lolin_s2_mini
board_build.partitions = ${common.partitions}

[env:lolin_s2_mini-ssd1306]
platform = ${common.platform_esp32_pioarduino}
framework = arduino
board = lolin_s2_mini
board_build.partitions = ${common.partitions}
lib_deps = ${ssd1306.lib_deps}
build_flags = ${ssd1306.build_flags}

[env:lolin_s2_mini-ssd1306-psram]
platform = ${common.platform_esp32_pioarduino}
framework = arduino
board = lolin_s2_mini
board_build.partitions = ${common.partitions}
lib_deps =
	${ssd1306.lib_deps}
	${psram.lib_deps}
build_flags =
	${ssd1306.build_flags}
	${psram.build_flags}

[env:esp32-s3-supermini]
platform = ${common.platform_esp32_pioarduino}
framework = arduino
board = waveshare_esp32_s3_zero
board_build.mcu = esp32s3
board_build.partitions = ${common.partitions}
