; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_raw = true

[common]
platform_esp32_espressif = espressif32
platform_esp32_pioarduino = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
lib_deps =
build_flags =
partitions = default_ffat.csv

; MIXIN: Completely optional external 128x64 SSD1306 OLED screen for status
[display128x64]
lib_deps =
	adafruit/Adafruit SSD1306@^2.5.16
	adafruit/Adafruit GFX Library@^1.12.4
build_flags =
	-DENABLE_DISPLAY_128x64

; MIXIN: When present, use WS2812 RGBLED as "display"
[displayrgbled]
lib_deps =
	adafruit/Adafruit NeoPixel@^1.15.2
build_flags =
	-DENABLE_DISPLAY_RGBLED

; MIXIN: Completely optional PSRAM as destination for watch dump, falls back to flash
[psram]
lib_deps = 
	;tobozo/ESP32-PSRamFS@^1.0.7 ;Now included locally with patch for pioarduino
build_flags = -DENABLE_PSRAM

[env:esp32_s3_supermini]
platform = ${common.platform_esp32_pioarduino}
framework = arduino
board = esp32-s3-fh4r2 ; 4MB flash, 2MB psram
board_build.partitions = ${common.partitions}
lib_deps = 
	${common.lib_deps}
	${psram.lib_deps}
	; ${displayrgbled.lib_deps}
build_flags =
	${common.build_flags}
	${psram.build_flags}
	; ${displayrgbled.lib_deps}

[env:lolin_s2_mini]
platform = ${common.platform_esp32_pioarduino}
framework = arduino
board = lolin_s2_mini
board_build.mcu = esp32s2
board_build.partitions = ${common.partitions}
lib_deps = ${common.lib_deps}
build_flags = ${common.build_flags}

[env:lolin_s2_mini-display128x64]
platform = ${common.platform_esp32_pioarduino}
framework = arduino
board = lolin_s2_mini
board_build.mcu = esp32s2
board_build.partitions = ${common.partitions}
lib_deps = 
	${common.lib_deps}
	${display128x64.lib_deps}
build_flags =
	${common.build_flags}
	${display128x64.build_flags}

;; Build for the PCB in this repository
[env:PCB-wqv1-lolin-s2mini]
platform = ${common.platform_esp32_pioarduino}
framework = arduino
board = lolin_s2_mini
board_build.mcu = esp32s2
board_build.partitions = ${common.partitions}
lib_deps =
	${common.lib_deps}
	${display128x64.lib_deps}
	${psram.lib_deps}
build_flags =
	${common.build_flags}
	${display128x64.build_flags}
	${psram.build_flags}
	-DPIN_IRDA_TX=10
	-DPIN_IRDA_RX=13
	-DPIN_IRDA_SD=14
	-DPIN_I2C_SCL=35
	-DPIN_I2C_SDA=33
